import "./globals.css";
import { cn } from "@/lib/utils";
import { bebas, playfair, spectral } from "@/lib/fonts";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn(bebas.variable, spectral.variable, playfair.variable)}
      suppressHydrationWarning
    >
      <head />
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
